source 'http://rubygems.org'
ruby '2.5.3'
gem 'rails'
#gem 'couchrest_model'
#gem 'couch_tap'
gem 'mysql2'
gem 'json'
gem 'fastercsv'
gem 'bundler'
gem 'bcrypt-ruby', :require => 'bcrypt'
gem 'rest-client'
gem "paperclip" 
gem 'rake'
gem 'passenger' 
gem 'spreadsheet'
gem 'rb-readline'
gem 'chronic'
gem 'whenever',  :require => false 
gem 'activerecord-session_store'
gem 'listen'